<a href="https://colab.research.google.com/github/ShriVarshaan/computervision-learning-log/blob/main/tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
#Creating a 0D tensor
tensor_zero_d = tf.constant(4)

In [3]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_two_d = tf.constant([[2,0,-3], [1,2,0]])
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3]
 [ 1  2  0]], shape=(2, 3), dtype=int32)


In [6]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]]
], dtype = tf.float32)

print(tensor_three_d)

tf.Tensor(
[[[ 1.  2.  0.]
  [ 3.  5.  1.]]

 [[10.  2.  0.]
  [ 1.  0.  2.]]

 [[ 5.  8.  0.]
  [ 2.  7.  0.]]

 [[ 2.  1.  9.]
  [ 4. -3. 32.]]], shape=(4, 2, 3), dtype=float32)


In [7]:
print(tensor_three_d.dtype)
print(tensor_three_d.ndim) #The rank of a tensor is the same as ndim, not the same as the rank of matrix
print(tensor_three_d.shape)

<dtype: 'float32'>
3
(4, 2, 3)


In [8]:
print(tf.cast(tensor_three_d, dtype=tf.int64)) #Doesn't change the original tensor, creates a copy instead

tf.Tensor(
[[[ 1  2  0]
  [ 3  5  1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int64)


In [9]:
print(tensor_three_d)

tf.Tensor(
[[[ 1.  2.  0.]
  [ 3.  5.  1.]]

 [[10.  2.  0.]
  [ 1.  0.  2.]]

 [[ 5.  8.  0.]
  [ 2.  7.  0.]]

 [[ 2.  1.  9.]
  [ 4. -3. 32.]]], shape=(4, 2, 3), dtype=float32)


In [10]:
print(tf.cast(tensor_three_d, dtype=tf.bool)) #Changes all the 0's to a False and everything else is true

tf.Tensor(
[[[ True  True False]
  [ True  True  True]]

 [[ True  True False]
  [ True False  True]]

 [[ True  True False]
  [ True  True False]]

 [[ True  True  True]
  [ True  True  True]]], shape=(4, 2, 3), dtype=bool)


In [11]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [12]:
print(tf.cast(tensor_bool, dtype=tf.int32)) #Changes the true to 1 and false to 0

tf.Tensor([1 1 0], shape=(3,), dtype=int32)


In [13]:
tensor_string = tf.constant(["hello", "world", "hi"])
print(tensor_string)

tf.Tensor([b'hello' b'world' b'hi'], shape=(3,), dtype=string)


In [14]:
print(tf.cast(tensor_string, dtype=tf.int32))

UnimplementedError: {{function_node __wrapped__Cast_device_/job:localhost/replica:0/task:0/device:CPU:0}} Cast string to int32 is not supported [Op:Cast] name: 

In [15]:
import numpy as np

In [16]:
numpy_array = np.array([1,2,4])
print(numpy_array)

[1 2 4]


In [17]:
numpy_array

array([1, 2, 4])

In [18]:
converted_tensor = tf.convert_to_tensor(numpy_array, dtype=tf.float32)
print(converted_tensor)

tf.Tensor([1. 2. 4.], shape=(3,), dtype=float32)


In [19]:
identity_matrix = tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.float32
) #Columns  = None will give square matrix and can set to anything to get something like this

In [20]:
print(5 * identity_matrix)

tf.Tensor(
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]], shape=(3, 5), dtype=float32)


In [21]:
print(tf.cast(identity_matrix, dtype=tf.bool))

tf.Tensor(
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]], shape=(3, 5), dtype=bool)


In [22]:
identity_matrix1 = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.float32
)

print(identity_matrix1)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 4, 3, 3), dtype=float32)


In [23]:
filled_tensor = tf.fill([3,3], 10, name="Test")
print(filled_tensor)

tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int32)


In [24]:
tf.size(filled_tensor) #returns a tensor with the number of elements in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [25]:
tf.size(identity_matrix1, out_type=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=72.0>

In [26]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 0.0,
    stddev = 1.0,
    dtype = tf.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[-0.38234636 -0.7359206 ]
 [-1.2847623  -1.4699532 ]
 [ 0.5012868  -0.52286476]], shape=(3, 2), dtype=float32)


In [27]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 100.0, #Gives us values that vary from the mean by around 100
    dtype = tf.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[198.20807  105.467415]
 [248.13388  148.49002 ]
 [129.65579  186.58865 ]], shape=(3, 2), dtype=float32)


In [28]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0, #Gives us values of mean of around 100
    stddev = 1.0, #Gives us values that vary from the mean by around 1
    dtype = tf.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[101.03877  101.11267 ]
 [100.27975  100.33208 ]
 [ 99.881935  99.7136  ]], shape=(3, 2), dtype=float32)


In [29]:
uniform_tensor = tf.random.uniform(
    [2,3],
    minval = 0,
    maxval = None, #defaults to 1
    dtype = tf.float32,
    seed = None,
    name = None
)

#All the values between the minval and the maxval have a 50% change of being in the tensor, whereas the normal has probability of mean occuring high and other elements lower like bell curve
print(uniform_tensor)

tf.Tensor(
[[0.68190503 0.48209405 0.51740825]
 [0.5695977  0.6380919  0.47981787]], shape=(2, 3), dtype=float32)


In [30]:
uniform_tensor = tf.random.uniform(
    [2,3],
    minval = 0,
    maxval = 100,
    dtype = tf.float32,
    seed = None,
    name = None
)

print(uniform_tensor)

tf.Tensor(
[[65.218506 51.64708  66.39074 ]
 [37.289368 13.407803 53.33184 ]], shape=(2, 3), dtype=float32)


In [31]:
#tf.random.set_seed(32) #Sets global seed
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4)) #We are not overriding the seed
#We are using both seeds together
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10))

#Run this multiple times

tf.Tensor(
[[9.565817   2.6681077  9.977978  ]
 [8.45893    0.30183673 2.8946888 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[7.4967327 8.196321  2.8542209]
 [9.19063   0.6549144 5.336362 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2.2864485 3.083526  5.0533247]
 [7.9322624 1.8805671 9.963772 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5.0103083 9.532189  2.740736 ]
 [1.8468869 9.631305  2.5154054]], shape=(2, 3), dtype=float32)


In [32]:
tf.random.set_seed(32) #Sets global seed
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4)) #We are not overriding the seed
#We are using both seeds together
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10))

#Run this multiple times

tf.Tensor(
[[2.044133  8.605606  2.7524328]
 [7.449169  8.96482   5.4136252]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2.3985982  0.838114   6.9565954 ]
 [2.9534018  0.55855393 6.092435  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[3.184303   4.785669   4.6754646 ]
 [0.18546939 4.510329   9.545688  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5.4520597 1.3372338 4.523267 ]
 [1.5582252 9.621073  8.151463 ]], shape=(2, 3), dtype=float32)


In [33]:
#We get these different outputs as the local seed only determines the random generation for that op
#If the global seed is not set tf uses a non-deterministic seed source
#Which means each local seed will behave differently each time it is run unless a global seed is set

In [34]:
#Just the global seed set should make it reproducible but if we insert a new random op the sequencing of the stuff changes

#This is because we are advancing the random number generators state

In [35]:
tensor_to_index = tf.constant([4,3,6,8,3,1])
print(tensor_to_index)

tf.Tensor([4 3 6 8 3 1], shape=(6,), dtype=int32)


In [36]:
print(tensor_to_index[2:5])

tf.Tensor([6 8 3], shape=(3,), dtype=int32)


In [37]:
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3]
 [ 1  2  0]], shape=(2, 3), dtype=int32)


In [38]:
tensor_two_d = tf.constant(
    [[1,2,0],
     [3,5,-1],
     [1,5,6],
     [2,3,8]]
)

In [39]:
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [40]:
print(tensor_two_d[2,1]) # [row, column] if we give these indices we get the value there

tf.Tensor(5, shape=(), dtype=int32)


In [41]:
#If we want everything from a few rows and a few columns we just give the inputs to the row and column
# as a range using the :

print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [42]:
print(tensor_two_d[0:3, 1])

tf.Tensor([2 5 5], shape=(3,), dtype=int32)


In [43]:
x_abs = tf.constant([-2.25, 3.25])
print(tf.abs(x_abs)) #Turns all the negative values into positive values

tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)


In [44]:
#Absolute value of a complex value in a tensor is calculated as root (a^2 + b^2), a + bj, j is i in cs

x = tf.constant([-2.25 + 4.75j])
print(tf.abs(x))

tf.Tensor([5.25594901], shape=(1,), dtype=float64)


In [45]:
x1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x2 = tf.constant([7], dtype=tf.int32)

x1+x2



<tf.Tensor: shape=(6,), dtype=int32, numpy=array([12, 10, 13, 13, 11, 13], dtype=int32)>

### Basic tensor concepts

Rank -- number of dimensions the tensor has, can also be taught of as the length of the shape tensor of the original tensor, len(tensor_name.shape)

Axis -- Refers to each dimension

In [46]:
dd = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])



In [47]:
#Each element among the first axis is an array

In [48]:
dd[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [49]:
dd[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [50]:
dd[2]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9], dtype=int32)>

In [51]:
#Each element along the second axis is a number

In [52]:
dd[0][0] #And so on

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [53]:
#The elements of the last axis in a tensor is always a number.

In [54]:
dd.shape

TensorShape([3, 3])

In [55]:
y = tf.constant(
    [
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,12,43,14],
            [55,96,47,38],
            [99,1,110,1]
        ]
    ]
)


In [56]:
y.shape

TensorShape([2, 3, 4])

In [57]:
#In this tensor Axis 0 has size 2
# Axis 1 has size 3
# Axis 2 has size 4

In [58]:
y

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  12,  43,  14],
        [ 55,  96,  47,  38],
        [ 99,   1, 110,   1]]], dtype=int32)>

In [59]:
y[0]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [60]:
y[:, 1]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 5,  6,  7,  8],
       [55, 96, 47, 38]], dtype=int32)>

In [61]:
y[:, :, 2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  3,   7,  11],
       [ 43,  47, 110]], dtype=int32)>

In [62]:
tf.random.set_seed(42)
t = tf.random.normal(
    shape = [3,4,2],
    mean = 50,
    stddev = 5,
    seed = 42
)

In [63]:
print(t)

tf.Tensor(
[[[56.574387 49.22892 ]
  [54.55694  46.00428 ]
  [49.456234 51.42184 ]
  [53.83081  46.894356]]

 [[54.98716  51.09796 ]
  [44.600666 40.062584]
  [57.80185  49.154526]
  [43.109756 48.509922]]

 [[54.205    54.612747]
  [47.58104  41.514374]
  [50.476826 49.466232]
  [41.08036  58.57296 ]]], shape=(3, 4, 2), dtype=float32)


In [64]:
t[0] # Get me the 0th element along axis 0

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[56.574387, 49.22892 ],
       [54.55694 , 46.00428 ],
       [49.456234, 51.42184 ],
       [53.83081 , 46.894356]], dtype=float32)>

In [65]:
t[0][0] #Get me the 0th element along axis 1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([56.574387, 49.22892 ], dtype=float32)>

In [66]:
t[0][0][0] #Get me the 0th element along axis 2

<tf.Tensor: shape=(), dtype=float32, numpy=56.57438659667969>

In [67]:
t[:] #Get me all the elements along axis 0

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[56.574387, 49.22892 ],
        [54.55694 , 46.00428 ],
        [49.456234, 51.42184 ],
        [53.83081 , 46.894356]],

       [[54.98716 , 51.09796 ],
        [44.600666, 40.062584],
        [57.80185 , 49.154526],
        [43.109756, 48.509922]],

       [[54.205   , 54.612747],
        [47.58104 , 41.514374],
        [50.476826, 49.466232],
        [41.08036 , 58.57296 ]]], dtype=float32)>

In [68]:
t[:, 0] #For all the axis 0 elements get the 0th row

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[56.574387, 49.22892 ],
       [54.98716 , 51.09796 ],
       [54.205   , 54.612747]], dtype=float32)>

In [69]:
t[:, :, 1]
# For all slices and all rows get me the second column

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[49.22892 , 46.00428 , 51.42184 , 46.894356],
       [51.09796 , 40.062584, 49.154526, 48.509922],
       [54.612747, 41.514374, 49.466232, 58.57296 ]], dtype=float32)>

In [70]:
t.shape

TensorShape([3, 4, 2])

In [71]:
print(t)

tf.Tensor(
[[[56.574387 49.22892 ]
  [54.55694  46.00428 ]
  [49.456234 51.42184 ]
  [53.83081  46.894356]]

 [[54.98716  51.09796 ]
  [44.600666 40.062584]
  [57.80185  49.154526]
  [43.109756 48.509922]]

 [[54.205    54.612747]
  [47.58104  41.514374]
  [50.476826 49.466232]
  [41.08036  58.57296 ]]], shape=(3, 4, 2), dtype=float32)


In [72]:
tf.math.argmax(t, axis=0)

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 2],
       [0, 0],
       [1, 0],
       [0, 2]])>

###Tensorflow functions

In [73]:
tensor_three_d = tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [5,8,0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4, -3, 32]
    ]
])

print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis = 0).shape)

(4, 2, 3)
(1, 4, 2, 3)


In [74]:
x = tf.constant([2,3,4,5])
print(x.shape)
tf.expand_dims(x, axis = 1).shape

(4,)


TensorShape([4, 1])

In [75]:
print(tf.expand_dims(x, axis = 1))

tf.Tensor(
[[2]
 [3]
 [4]
 [5]], shape=(4, 1), dtype=int32)


The squeeze methods removes the dimension of size 1

In [76]:
x_expanded = tf.expand_dims(x, axis = 0)
x_expanded

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[2, 3, 4, 5]], dtype=int32)>

In [77]:
x_squeezed = tf.squeeze(x_expanded)
x_squeezed

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [78]:
tf.squeeze(x_expanded, axis = 1) #Can only squeeze the dimension of size 1

InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:CPU:0}} Can not squeeze dim[1], expected a dimension of 1, got 4 [Op:Squeeze] name: 

In [79]:
x.shape

TensorShape([4])

In [80]:
x = tf.constant([[3,5,6,6],
                 [1,2,3,4],
                 [4,9,7,2]])
tf.reshape(x, [1,-1]) #When we put -1 tensflow automatically picks the correct value

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[3, 5, 6, 6, 1, 2, 3, 4, 4, 9, 7, 2]], dtype=int32)>

In [81]:
t1 = tf.constant(
    [
        [1,2,3],
        [4,5,6]
    ]
)

t2 = tf.constant(
    [
        [7,8,9],
        [10,11,12]
    ]
)

tf.concat([t1, t2], 1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [82]:

a = tf.constant([99, 999, 999])
b= tf.constant([322, 411, 888])
c= tf.constant([523, 622, 666])

tf.stack([a, b, c], 0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 99, 999, 999],
       [322, 411, 888],
       [523, 622, 666]], dtype=int32)>

In [83]:
tf.stack([a, b, c], 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 99, 322, 523],
       [999, 411, 622],
       [999, 888, 666]], dtype=int32)>

In [84]:
a = tf.constant([[1,2,3], [4,5,6]])
b = tf.constant([[7,8,9], [10,11,12]])

tf.stack([a, b], axis = 2)


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

###Practicing axes from chatgpt

In [85]:
x = tf.constant([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
# Shape: (2, 2, 3)
# 2 batches, each batch = 2x3 matrix


In [86]:
tf.math.reduce_sum(x, axis = 0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [87]:
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [88]:
tf.math.reduce_sum(x, axis = 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [17, 19, 21]], dtype=int32)>

In [89]:
tf.math.reduce_mean(x, axis = 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 8, 11]], dtype=int32)>

In [90]:
x = tf.constant([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

a = tf.constant([
    [1,2,3],
    [4,5,6]
])

b = tf.constant([
    [7,8,9],
    [10,11,12]
])

In [91]:
tf.stack([a,b], axis = 2)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [92]:
tf.concat([a,b], axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [93]:
t1 = tf.constant(
    [
        [1,2,3],
        [4,5,6],
        [5,6,2],
        [1,2,1]
    ]
)

t2 = tf.constant(
    [
        [7,8,9],
        [10,11,12],
        [0,0,2],
        [-1, 5, 2]
    ]
)


In [94]:
tf.stack([t1, t2, t1], axis = 1)

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [ 1,  2,  3]],

       [[ 4,  5,  6],
        [10, 11, 12],
        [ 4,  5,  6]],

       [[ 5,  6,  2],
        [ 0,  0,  2],
        [ 5,  6,  2]],

       [[ 1,  2,  1],
        [-1,  5,  2],
        [ 1,  2,  1]]], dtype=int32)>

In [95]:
x = tf.constant([[[[2,3,4,5]]]])
x.shape

TensorShape([1, 1, 1, 4])

In [96]:
tf.squeeze(x).shape

TensorShape([4])

Notice how the shape of the tensor changes when we concatenate, the axis along with which we concat gets added up.

ex) if t1.shape == (3,2,5)
       t2.shape == (3,2,5)

When we concat t1 and t2 along axis = 0, the shape will be (6,2,5)

When we concat t1 and t2 along axis = 1, the shape will be (3,4,5)

When we concat t1 and t2 along axis = 2, the shape will be (3,2,10)


Also when we concat, the shape must exactly match up on all dimensions except for the one along which we are concating. The one along which we are concating may or may not match up but the others MUST match up

### Stacking

In stacking a new axis is created instead of adding up on the axis like concat.

If we have two tensors of shape (2,3) and we stack them along axis = 0, we get a new tensor of shape (2,2,3).

The shape in the new dimension created depends on the number of tensors we are stacking. In this case we stack two tensors so the shape is (2,2,3)
If we stacked t1, t2 and t1 it would've been (3,2,3) assuming the axis = 0

In [100]:
t1.shape

TensorShape([4, 3])

It is very easy to predict what the output must be when we figure out what the shape will be and work backwards from that instead of trying to figure out what the output will be directly

In [101]:
t1 = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

t2 = tf.constant([[13,14,15],
                  [16,17,18],
                  [19,20,21],
                  [22,23,24]])

tf.stack([t1, t2], axis = 2)

#INTUITION
"""
First we look at the shape of both our tensors which is (4,3). Now when we want to stack along axis = 2, we will create a tensor of shape (4,3,2). We get the 2 as we are stacking
two tensors.
Now we need to stack them, the only logical way to do this is the answer down below
"""

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18]],

       [[ 7, 19],
        [ 8, 20],
        [ 9, 21]],

       [[10, 22],
        [11, 23],
        [12, 24]]], dtype=int32)>

In [102]:
t1 = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

t2 = tf.constant([[13,14,15],
                  [16,17,18],
                  [19,20,21],
                  [22,23,24]])

tf.stack([t1, t2], axis = 1)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]], dtype=int32)>

In [103]:
t1 = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

t2 = tf.constant([[13,14,15],
                  [16,17,18],
                  [19,20,21],
                  [22,23,24]])

tf.stack([t1, t2], axis = 0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>