<a href="https://colab.research.google.com/github/ShriVarshaan/computervision-learning-log/blob/main/tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
#Creating a 0D tensor
tensor_zero_d = tf.constant(4)

In [5]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [7]:
tensor_two_d = tf.constant([[2,0,-3], [1,2,0]])
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3]
 [ 1  2  0]], shape=(2, 3), dtype=int32)


In [19]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]]
], dtype = tf.float32)

print(tensor_three_d)

tf.Tensor(
[[[ 1.  2.  0.]
  [ 3.  5.  1.]]

 [[10.  2.  0.]
  [ 1.  0.  2.]]

 [[ 5.  8.  0.]
  [ 2.  7.  0.]]

 [[ 2.  1.  9.]
  [ 4. -3. 32.]]], shape=(4, 2, 3), dtype=float32)


In [14]:
print(tensor_three_d.dtype)
print(tensor_three_d.ndim) #The rank of a tensor is the same as ndim, not the same as the rank of matrix
print(tensor_three_d.shape)

<dtype: 'int32'>
3
(4, 2, 3)


In [21]:
print(tf.cast(tensor_three_d, dtype=tf.int64)) #Doesn't change the original tensor, creates a copy instead

tf.Tensor(
[[[ 1  2  0]
  [ 3  5  1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int64)


In [22]:
print(tensor_three_d)

tf.Tensor(
[[[ 1.  2.  0.]
  [ 3.  5.  1.]]

 [[10.  2.  0.]
  [ 1.  0.  2.]]

 [[ 5.  8.  0.]
  [ 2.  7.  0.]]

 [[ 2.  1.  9.]
  [ 4. -3. 32.]]], shape=(4, 2, 3), dtype=float32)


In [23]:
print(tf.cast(tensor_three_d, dtype=tf.bool)) #Changes all the 0's to a False and everything else is true

tf.Tensor(
[[[ True  True False]
  [ True  True  True]]

 [[ True  True False]
  [ True False  True]]

 [[ True  True False]
  [ True  True False]]

 [[ True  True  True]
  [ True  True  True]]], shape=(4, 2, 3), dtype=bool)


In [24]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [25]:
print(tf.cast(tensor_bool, dtype=tf.int32)) #Changes the true to 1 and false to 0

tf.Tensor([1 1 0], shape=(3,), dtype=int32)


In [26]:
tensor_string = tf.constant(["hello", "world", "hi"])
print(tensor_string)

tf.Tensor([b'hello' b'world' b'hi'], shape=(3,), dtype=string)


In [28]:
print(tf.cast(tensor_string, dtype=tf.int32))

UnimplementedError: {{function_node __wrapped__Cast_device_/job:localhost/replica:0/task:0/device:CPU:0}} Cast string to int32 is not supported [Op:Cast] name: 

In [29]:
import numpy as np

In [30]:
numpy_array = np.array([1,2,4])
print(numpy_array)

[1 2 4]


In [31]:
numpy_array

array([1, 2, 4])

In [34]:
converted_tensor = tf.convert_to_tensor(numpy_array, dtype=tf.float32)
print(converted_tensor)

tf.Tensor([1. 2. 4.], shape=(3,), dtype=float32)


In [39]:
identity_matrix = tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.float32
) #Columns  = None will give square matrix and can set to anything to get something like this

In [40]:
print(5 * identity_matrix)

tf.Tensor(
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]], shape=(3, 5), dtype=float32)


In [41]:
print(tf.cast(identity_matrix, dtype=tf.bool))

tf.Tensor(
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]], shape=(3, 5), dtype=bool)


In [45]:
identity_matrix1 = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.float32
)

print(identity_matrix1)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 4, 3, 3), dtype=float32)


In [48]:
filled_tensor = tf.fill([3,3], 10, name="Test")
print(filled_tensor)

tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int32)


In [50]:
tf.size(filled_tensor) #returns a tensor with the number of elements in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [52]:
tf.size(identity_matrix1, out_type=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=72.0>

In [55]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 0.0,
    stddev = 1.0,
    dtype = tf.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[ 0.5177638  -0.9499917 ]
 [-0.33650762  0.69638777]
 [ 0.8975706  -0.1787923 ]], shape=(3, 2), dtype=float32)


In [57]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 100.0, #Gives us values that vary from the mean by around 100
    dtype = tf.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[ 65.35202  79.41   ]
 [169.25055 109.05708]
 [105.71375 149.64539]], shape=(3, 2), dtype=float32)


In [58]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0, #Gives us values of mean of around 100
    stddev = 1.0, #Gives us values that vary from the mean by around 1
    dtype = tf.float32,
    seed = None,
    name = None
)

print(random_tensor)

tf.Tensor(
[[ 99.26829   99.75984 ]
 [100.11934  100.605835]
 [ 98.96017  100.49157 ]], shape=(3, 2), dtype=float32)


In [59]:
uniform_tensor = tf.random.uniform(
    [2,3],
    minval = 0,
    maxval = None, #defaults to 1
    dtype = tf.float32,
    seed = None,
    name = None
)

#All the values between the minval and the maxval have a 50% change of being in the tensor, whereas the normal has probability of mean occuring high and other elements lower like bell curve
print(uniform_tensor)

tf.Tensor(
[[0.46503735 0.22355759 0.46969712]
 [0.30542326 0.60566664 0.33624852]], shape=(2, 3), dtype=float32)


In [62]:
uniform_tensor = tf.random.uniform(
    [2,3],
    minval = 0,
    maxval = 100,
    dtype = tf.float32,
    seed = None,
    name = None
)

print(uniform_tensor)

tf.Tensor(
[[ 6.0055017 51.265083  77.40809  ]
 [79.17391   15.138102  90.217995 ]], shape=(2, 3), dtype=float32)


In [75]:
#tf.random.set_seed(32) #Sets global seed
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4)) #We are not overriding the seed
#We are using both seeds together
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10))

#Run this multiple times

tf.Tensor(
[[7.058065  9.753601  7.282633 ]
 [9.075569  2.1974826 0.6333399]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5.4747653 8.022779  6.121669 ]
 [2.9681206 4.8530397 9.182172 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2.0592546 5.765331  6.7363667]
 [7.6667953 5.8978424 7.9674363]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[9.367114  6.2011137 2.6261568]
 [6.4392304 8.944654  1.9541836]], shape=(2, 3), dtype=float32)


In [78]:
tf.random.set_seed(32) #Sets global seed
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4)) #We are not overriding the seed
#We are using both seeds together
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10, seed=4))
print(tf.random.uniform([2,3], minval=0, maxval=10))

#Run this multiple times

tf.Tensor(
[[2.044133  8.605606  2.7524328]
 [7.449169  8.96482   5.4136252]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2.3985982  0.838114   6.9565954 ]
 [2.9534018  0.55855393 6.092435  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[3.184303   4.785669   4.6754646 ]
 [0.18546939 4.510329   9.545688  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5.4520597 1.3372338 4.523267 ]
 [1.5582252 9.621073  8.151463 ]], shape=(2, 3), dtype=float32)


In [79]:
#We get these different outputs as the local seed only determines the random generation for that op
#If the global seed is not set tf uses a non-deterministic seed source
#Which means each local seed will behave differently each time it is run unless a global seed is set

In [81]:
#Just the global seed set should make it reproducible but if we insert a new random op the sequencing of the stuff changes

#This is because we are advancing the random number generators state

In [82]:
tensor_to_index = tf.constant([4,3,6,8,3,1])
print(tensor_to_index)

tf.Tensor([4 3 6 8 3 1], shape=(6,), dtype=int32)


In [84]:
print(tensor_to_index[2:5])

tf.Tensor([6 8 3], shape=(3,), dtype=int32)


In [85]:
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3]
 [ 1  2  0]], shape=(2, 3), dtype=int32)


In [89]:
tensor_two_d = tf.constant(
    [[1,2,0],
     [3,5,-1],
     [1,5,6],
     [2,3,8]]
)

In [90]:
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [91]:
print(tensor_two_d[2,1]) # [row, column] if we give these indices we get the value there

tf.Tensor(5, shape=(), dtype=int32)


In [92]:
#If we want everything from a few rows and a few columns we just give the inputs to the row and column
# as a range using the :

print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [93]:
print(tensor_two_d[0:3, 1])

tf.Tensor([2 5 5], shape=(3,), dtype=int32)
